const ADJECTIVES = [
  "Midnight",
  "Velvet",
  "Electric",
  "Golden",
  "Cosmic",
  "Neon",
  "Crystal",
  "Lunar",
  "Solar",
  "Mystic",
  "Atomic",
  "Dreamy",
  "Funky",
  "Groovy",
  "Euphoric",
  "Radiant",
  "Sonic",
  "Stellar",
  "Vivid",
  "Chill",
  "Blazing",
  "Ethereal",
  "Hypnotic",
  "Infinite",
  "Pacific",
  "Tropical",
  "Arctic",
  "Crimson",
  "Amber",
  "Sapphire",
]

const NOUNS = [
  "Beats",
  "Waves",
  "Vibes",
  "Echoes",
  "Rhythms",
  "Melodies",
  "Harmonics",
  "Frequencies",
  "Sessions",
  "Grooves",
  "Pulses",
  "Sounds",
  "Tones",
  "Mixtape",
  "Jams",
  "Anthems",
  "Chords",
  "Riffs",
  "Loops",
  "Basslines",
  "Symphonies",
  "Serenades",
  "Ballads",
  "Overtures",
  "Cadences",
  "Refrains",
  "Crescendos",
  "Preludes",
  "Sonatas",
  "Nocturnes",
]

export function generatePlaylistName(): string {
  const adj = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)]
  return `${adj} ${noun}`
}
